### ISSUE TITLE
Empty predictive sets

### ISSUE THREAD

**Issue by lsunderm** [aangelopoulos/conformal_classification#5]
Hi Anastasios,

thanks for providing the code for your conformal classification work. 

When applying the code to a different dataset and validating it on some test data, I found that in some cases the predictive set is empty. This seems to be caused by line 170 in the function `gcq` in the file `conformal.py`. When `sizes_base` is `1` and `np.random.random(V.shape)` is larger or equal than `V`, this results in values of `0`.
I'm not entirely sure whether the `gcp` function is called only during validation or whether it also has an influence on finding the parameters used for the classification, so I wanted to make you aware of this issue.

Best,
Linda

**Comment by aangelopoulos** [comment]
Hi Linda,

  Thank you for pointing this out! Sets of size zero are a mathematical oddity sometimes needed to achieve exact coverage (in the case we picked a coverage level lower than the model's accuracy). This is expected behavior, but I forgot to note it in the documentation.

  For an immediate fix, you can just set randomized=False. Then sets of size zero shouldn't happen anymore, although the coverage will be slightly conservative.  

  In the longer term (over the next few days) I'll try to put another flag called "allow-zero-sets" or something that just never allows sets of size zero. This should be less conservative than randomized=False.

  Let me know if this fixed your problem :)

Best,
Anastasios

**Comment by lsunderm** [comment]
Hi Anastasios,

thanks for your quick answer, explanation and suggestion! This fixes my problem for now, I'll use `randomized=False` until you've introduced the new flag.

Best,
Linda

**Comment by aangelopoulos** [comment]
Hi Linda,
  Apologies for the wait! You can see the new flag in example.py.  :)
Best,
Anastasios
